# Generated by Django 4.1.2 on 2022-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
    ]
