# Generated by Django 4.1.2 on 2022-10-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
